{% set name = "bson" %}
{% set version = "0.5.10" %}
{% set sha256 = "fef2a86682570c3622519ddafb7477e9b876d440eba4e04017b1a5f3b49ccc27" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/py-bson/bson/archive/refs/tags/{{version}}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - setuptools
    - pip
    - wheel
  run:
    - python
    - six
    - python-dateutil >=2.4.0

test:
  source_files:
    - bson/tests
  imports:
    - bson
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest -v  # [py<312]
    # These test files use assertEquals, removed in python 3.12.
    - pytest -v --ignore="bson/tests/test_array.py" --ignore="bson/tests/test_random_tree.py" # [py>=312]

about:
  home: https://github.com/py-bson/bson
  dev_url: https://github.com/py-bson/bson
  doc_url: https://github.com/py-bson/bson/blob/master/README.rst
  summary: Independent BSON codec for Python that doesn't depend on MongoDB.
  description: |
    Independent BSON codec for Python that doesn't depend on MongoDB. 
    The bson ObjectId implementation is forked from the PyMongo project,
    licensed under the Version 2.0 Apache License.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - robmcmullen
    - ChrisBarker-NOAA
