{% set name = "bson" %}
{% set version = "0.5.8" %}
{% set sha256 = "13fb1e5486a611374a06177663c2ab878f0c192c8fc8765a63dfef86859006c9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - six
    - python-dateutil>=2.4.0

test:
  imports:
    - bson

about:
  summary: Independent BSON codec for Python that doesn't depend on MongoDB.
  home: https://github.com/py-bson/bson
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - robmcmullen
    - ChrisBarker-NOAA
