{% set name = "bson" %}
{% set version = "0.5.4" %}
{% set sha256 = "671dc3dcb8b8e1cef2a8fa7251ed15488f330ff7b009268ecf9f526737c1e739" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - six
    - pytz

test:
  imports:
    - bson

about:
  summary: Independent BSON codec for Python that doesn't depend on MongoDB.
  home: https://github.com/py-bson/bson
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - robmcmullen
    - ChrisBarker-NOAA
