travis:
  secure:
    BINSTAR_TOKEN: ggNKeuHr4pw1oxsXXKg2QJcehRhHX55mRF3mRM9qaija72tsDE/NhaRwst8armxM4sB+90PeORovznzrtrpgdU2K005nkeE4X39+jcIEW2GJVSknHja1X1D9Wri4+qNdENiGrV/FxmsP1ybshodIjnq9CbXsDo04rA6axDNrEz44yW63v+rzJOgasjFu5yEEijF0SQdtdclx3ahM4J54UA7C5rf/VzdPxPtH8J7qysRDfH1dfucWwA/xSlxw46PRR1oSFPLTk7uw+SqKhB9D0wsRGotb1dWATte4xSqoNl1wtXYocsKMUV2WpK6mDO6i7/Z0pMa/Z/5Ujuh9ifI97e7tgQYsGNkdZL+AdUXWX60AJPDzNTPI31DIC2qT6hvzS4SwpHs+H+Yhk4XkzQxxeUKZeEQC6hAGlqd7r+qlfO0ibjmu8Ivo2iRujzcTYFkuCwYmW30CnNFwel1A6brCk1sn6/r/+HVo6l6r0PH/YqEbeRx7FEDKGFc991C42fjzfMaUvy+ELT5Z4Wew/Ca9URSrB10lFev23GWP5Pjext+3WMNgguCrDEsrzzo30RWMbyCA0ubxmJWRcGAsJom6Y9wINSVWBuMcLQ/W3m/8nM1rGh59J4nk2pjyqnwnMayTJ4vAYgF8nP/gCmgsvnrFYQulHvkkICpSrVQygiKLZ2Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
