travis:
  secure:
    BINSTAR_TOKEN: a8Wo3ttBObmfojMGkFZghsyaMS6joBjvI99s4TBDA44z/CJb38yzwo2YW8qoOQy8eyn5DL4Ssz9zGEllRzI9NN6ZgzdwjVF+dFsWcOa+JYmJOgtA5wZv4NwZ37RG0kF42vwtTIzSz4ZPmSHrDY9xh2cTE40JdvV2Qvj7Nn6KMVN7YShWOOSlhfQruYPpFNEtHHehLdHrqjL+P2U7g+6vUMGCEOOAHXIe2KR+BXbHBNZL2pffha7ESLc2lfa+np2EQnvsKS34QywgFiHkhIrO2RNQQD4TTXwNOWO5YQQ7P5XfQ/T7vL0lMPwYp89qrWJlE6uokx8n3wmWz++OCDPBwUODc6NixYQIreWh42Prl0yzyxCzwGgH9iq82RundUfWWr97AuWi/iDEffHmV+YiJyfgBfEJymet8QlxSEHcJ6vBT0k9Rl6hf3yx5XwjHzKMH8AvcZ2VTyeHD+azmUS+mYyhkxvzbLEzXJ7l1JR3Nu8ZOo+ArwEjG1mIV785YwfZBq4+a5bZTVtdW5Enb/qE0EW0eMqM1XtmJFRE87hjP01r/wsJdGBiWA7fVVFjYEuXb9s9qO4BeUZArgWp2IOcSCOpN6HHGa4IqYHl0+TIp3j0KE+CHMb+3THGaW7z+0rTOo0f6HhTnaD9+GXse4/UaSzemTv9ZE0eq46tmKWs/Eg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
